### ISSUE TITLE
Views checklist

### ISSUE THREAD

**Issue by C4L86** [omahacodeschool/old_vinyl-archive#110]
- [x] Homepage (Album index)
  - [ ] Jillian
  - [x] Chris
- [x] Album show
  - [x] Jillian
  - [ ] Chris
- [x] Artist index
  - [x] Jillian
  - [ ] Chris
- [x] Artist show
  - [x] Jillian
  - [ ] Chris
- [x] Area index
  - [ ] Jillian
  - [x] Chris
- [x] Area show
  - [ ] Jillian
  - [x] Chris
- [x] Genre index 
  - [ ] Jillian
  - [x] Chris
- [x] Genre show
  - [ ] Jillian
  - [x] Chris
- [x] Decade index
  - [ ] Jillian
  - [x] Chris
- [ ] Decade show
  - [ ] Jillian
  - [x] Chris
- [x] Format index
  - [ ] Jillian
  - [x] Chris
- [x] Format show
  - [ ] Jillian
  - [x] Chris
- [ ] Album addition page (user)
  - [x] Jillian
  - [ ] Chris
- [ ] Review submissions (admin)
  - [ ] Jillian
  - [ ] Chris
